### ISSUE TITLE
Pulse/Websocket issue

### ISSUE THREAD

**Issue by kirotnes** [slasktrat/com.tibber#12]
There appears to a problem with the management of web socket connections when streaming Pulse data. Users are basically flooding the Tibber API - creating new connections non-stop.

Not really sure why this is happening but there might be some leakage due to this: https://github.com/slasktrat/com.tibber/blob/master/lib/tibber.js#L77

I guess "reconnect" can be false here since connections are reestablished when data are missing anyways. 

Wouldn't it be better to just let client handle reconnections itself? The server will disconnect the client after 1 minute of inactivity (meaning nothing pushed over the connection) but from my experience the ApolloClient/Websocket will reestablish the connection (when reconnect=true) and also the GraphQl subscription.

**Comment by slasktrat** [comment]
Auch! Did not mean for that to happen :/ 

The manual reestablishment was implemented in the latest version due to #8. I left the "reconnect" to true, as my failsafe does not trigger until 10 minutes without data. And I'm calling unsubscribe before reestablish trying to prevent exactly this. But seems the built-in reconnect does not work properly anyway so I will set it to false and submit new version at once. (Note: It takes normally a couple of days for Athom to approve the update)

**Comment by kirotnes** [comment]
Ok, cool. Thanks for the fast response!
